# Generated by Django 5.2.7 on 2025-11-06 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('full_url', models.URLField(max_length=1000)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='interaction_timesta_c8502e_idx'), models.Index(fields=['method'], name='interaction_method_ad332e_idx'), models.Index(fields=['path'], name='interaction_path_d31c3b_idx'), models.Index(fields=['user'], name='interaction_user_id_7a975a_idx'), models.Index(fields=['status_code'], name='interaction_status__125421_idx')],
            },
        ),
    ]
