# Generated by Django 5.2.7 on 2025-11-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinteraction',
            name='query_params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
