# Generated by Django 5.2.7 on 2025-11-05 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('glucose_avg', models.FloatField()),
                ('glucose_std', models.FloatField()),
                ('time_in_range', models.FloatField()),
                ('time_below_range', models.FloatField()),
                ('time_above_range', models.FloatField()),
                ('total_bolus', models.FloatField()),
                ('total_meals', models.IntegerField()),
                ('total_carbs', models.IntegerField()),
                ('total_proteins', models.IntegerField()),
                ('total_fats', models.IntegerField()),
                ('total_calories', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
