# Generated by Django 5.2.7 on 2025-11-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='cgm_coverage',
            field=models.IntegerField(default=100, help_text='Percent of the day covered by CGM readings (0–100)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='glucose_avg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='glucose_std',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='time_above_range',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='time_below_range',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='time_in_range',
            field=models.IntegerField(),
        ),
    ]
