# Generated by Django 5.2.7 on 2025-11-05 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_dailysummary_cgm_coverage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='cgm_coverage',
            field=models.IntegerField(help_text='Percent of the period covered by CGM readings (0–100)'),
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose_avg', models.IntegerField()),
                ('glucose_std', models.IntegerField()),
                ('time_in_range', models.IntegerField()),
                ('time_below_range', models.IntegerField()),
                ('time_above_range', models.IntegerField()),
                ('cgm_coverage', models.IntegerField(help_text='Percent of the period covered by CGM readings (0–100)')),
                ('total_bolus', models.FloatField()),
                ('total_meals', models.IntegerField()),
                ('total_carbs', models.IntegerField()),
                ('total_proteins', models.IntegerField()),
                ('total_fats', models.IntegerField()),
                ('total_calories', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='QuarterlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose_avg', models.IntegerField()),
                ('glucose_std', models.IntegerField()),
                ('time_in_range', models.IntegerField()),
                ('time_below_range', models.IntegerField()),
                ('time_above_range', models.IntegerField()),
                ('cgm_coverage', models.IntegerField(help_text='Percent of the period covered by CGM readings (0–100)')),
                ('total_bolus', models.FloatField()),
                ('total_meals', models.IntegerField()),
                ('total_carbs', models.IntegerField()),
                ('total_proteins', models.IntegerField()),
                ('total_fats', models.IntegerField()),
                ('total_calories', models.IntegerField()),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-quarter'],
                'unique_together': {('user', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='RollingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose_avg', models.IntegerField()),
                ('glucose_std', models.IntegerField()),
                ('time_in_range', models.IntegerField()),
                ('time_below_range', models.IntegerField()),
                ('time_above_range', models.IntegerField()),
                ('cgm_coverage', models.IntegerField(help_text='Percent of the period covered by CGM readings (0–100)')),
                ('total_bolus', models.FloatField()),
                ('total_meals', models.IntegerField()),
                ('total_carbs', models.IntegerField()),
                ('total_proteins', models.IntegerField()),
                ('total_fats', models.IntegerField()),
                ('total_calories', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('period_days', models.IntegerField(help_text='Number of days in the rolling period')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-end_date', 'period_days'],
                'unique_together': {('user', 'end_date', 'period_days')},
            },
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose_avg', models.IntegerField()),
                ('glucose_std', models.IntegerField()),
                ('time_in_range', models.IntegerField()),
                ('time_below_range', models.IntegerField()),
                ('time_above_range', models.IntegerField()),
                ('cgm_coverage', models.IntegerField(help_text='Percent of the period covered by CGM readings (0–100)')),
                ('total_bolus', models.FloatField()),
                ('total_meals', models.IntegerField()),
                ('total_carbs', models.IntegerField()),
                ('total_proteins', models.IntegerField()),
                ('total_fats', models.IntegerField()),
                ('total_calories', models.IntegerField()),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-week'],
                'unique_together': {('user', 'year', 'week')},
            },
        ),
    ]
