# Generated by Django 5.2.7 on 2025-11-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_rename_cgm_coverage_dailysummary_daily_cgm_coverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollingsummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
