# Generated by Django 5.2.7 on 2025-11-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0005_rollingsummary_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='agp',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='agp',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterlysummary',
            name='agp',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rollingsummary',
            name='agp',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='agp',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
