# Generated by Django 5.2.7 on 2025-11-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0006_dailysummary_agp_monthlysummary_agp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='agp_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='agp_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterlysummary',
            name='agp_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rollingsummary',
            name='agp_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='agp_summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
