# Generated by Django 5.2.7 on 2025-11-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0007_dailysummary_agp_summary_monthlysummary_agp_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysummary',
            name='avg_fall_asleep_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='avg_wake_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='daily_deep_sleep_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='daily_rem_sleep_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='daily_sleep_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterlysummary',
            name='avg_fall_asleep_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterlysummary',
            name='avg_wake_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterlysummary',
            name='daily_deep_sleep_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterlysummary',
            name='daily_rem_sleep_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterlysummary',
            name='daily_sleep_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rollingsummary',
            name='avg_fall_asleep_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rollingsummary',
            name='avg_wake_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rollingsummary',
            name='daily_deep_sleep_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rollingsummary',
            name='daily_rem_sleep_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rollingsummary',
            name='daily_sleep_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='avg_fall_asleep_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='avg_wake_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='daily_deep_sleep_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='daily_rem_sleep_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='daily_sleep_duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
