# Generated by Django 5.2.7 on 2025-11-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0008_monthlysummary_avg_fall_asleep_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysummary',
            name='agp',
        ),
        migrations.RemoveField(
            model_name='dailysummary',
            name='agp_summary',
        ),
    ]
