# Generated by Django 5.2.7 on 2025-11-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0009_remove_dailysummary_agp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysummary',
            name='agp_trends',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterlysummary',
            name='agp_trends',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rollingsummary',
            name='agp_trends',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='agp_trends',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
