# Generated by Django 5.2.7 on 2025-11-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0010_monthlysummary_agp_trends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysummary',
            name='daily_deep_sleep_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysummary',
            name='daily_rem_sleep_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysummary',
            name='daily_sleep_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlysummary',
            name='daily_deep_sleep_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlysummary',
            name='daily_rem_sleep_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quarterlysummary',
            name='daily_sleep_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rollingsummary',
            name='daily_deep_sleep_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rollingsummary',
            name='daily_rem_sleep_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rollingsummary',
            name='daily_sleep_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklysummary',
            name='daily_deep_sleep_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklysummary',
            name='daily_rem_sleep_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklysummary',
            name='daily_sleep_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
