# Generated by Django 5.2.7 on 2025-11-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='glucose_target_high',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='glucose_target_low',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='glucose_target_very_high',
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='glucose_target_very_low',
            field=models.IntegerField(default=54),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
