# Generated by Django 5.2.7 on 2025-11-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersettings_glucose_target_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='timezone',
            field=models.CharField(default='Europe/Berlin', max_length=50),
        ),
    ]
