# Generated by Django 5.2.7 on 2025-11-03 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CgmEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value_mgdl', models.IntegerField()),
                ('five_minute_rate_mgdl', models.FloatField()),
                ('direction', models.CharField(choices=[('NONE', 'No trend'), ('DoubleUp', 'Double Up'), ('SingleUp', 'Single Up'), ('FortyFiveUp', 'Forty-Five Up'), ('Flat', 'Flat'), ('FortyFiveDown', 'Forty-Five Down'), ('SingleDown', 'Single Down'), ('DoubleDown', 'Double Down'), ('NotComputable', 'Not Computable'), ('RateOutOfRange', 'Rate Out of Range')], default='NONE', max_length=20)),
                ('device', models.CharField(default='Unknown', max_length=100)),
                ('source', models.CharField(default='Unknown', max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id'], name='diafit_back_user_id_31c081_idx')],
            },
        ),
    ]
