# Generated by Django 5.2.7 on 2025-11-03 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diafit_backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BolusEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_utc', models.DateTimeField(db_index=True, unique=True)),
                ('created_at_utc', models.DateTimeField()),
                ('updated_at_utc', models.DateTimeField()),
                ('value', models.FloatField()),
                ('event_type', models.CharField(max_length=100)),
                ('is_smb', models.BooleanField(default=False)),
                ('pump_type', models.CharField(max_length=100)),
                ('pump_serial', models.CharField(max_length=100)),
                ('pump_id', models.BigIntegerField()),
                ('source', models.CharField(default='Unknown', max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp_utc'],
                'indexes': [models.Index(fields=['user_id'], name='diafit_back_user_id_21995b_idx')],
            },
        ),
    ]
