# Generated by Django 5.2.7 on 2025-11-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diafit_backend', '0002_bolusentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolusentity',
            name='timestamp_utc',
            field=models.DateTimeField(),
        ),
    ]
