# Generated by Django 5.2.7 on 2025-11-04 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diafit_backend', '0003_alter_bolusentity_timestamp_utc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at_utc', models.DateTimeField()),
                ('meal_time_utc', models.DateTimeField()),
                ('calories', models.IntegerField(blank=True, default=0, null=True)),
                ('carbohydrates', models.IntegerField(default=0)),
                ('proteins', models.IntegerField(blank=True, default=0, null=True)),
                ('fats', models.IntegerField(blank=True, default=0, null=True)),
                ('impact_type', models.CharField(choices=[('SHORT', 'Short (≈2h)'), ('MEDIUM', 'Medium (≈4h)'), ('LONG', 'Long (≈6h)')], default='MEDIUM', max_length=10)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack')], default='SNACK', max_length=10)),
                ('is_valid', models.BooleanField(default=True)),
                ('image_id', models.CharField(blank=True, max_length=255, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='Unknown', max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-meal_time_utc'],
                'indexes': [models.Index(fields=['user_id'], name='diafit_back_user_id_7e3006_idx')],
            },
        ),
    ]
