# Generated by Django 5.2.7 on 2025-11-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diafit_backend', '0004_mealentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolusentity',
            name='pump_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bolusentity',
            name='pump_serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bolusentity',
            name='pump_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
