# Generated by Django 5.2.7 on 2025-11-07 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diafit_backend', '0005_alter_bolusentity_pump_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepSessionEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('source', models.CharField(default='Unknown', max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('total_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('deep_sleep_minutes', models.IntegerField(blank=True, null=True)),
                ('light_sleep_minutes', models.IntegerField(blank=True, null=True)),
                ('rem_sleep_minutes', models.IntegerField(blank=True, null=True)),
                ('awake_minutes', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SleepStageEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('stage', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Awake'), (2, 'Sleeping'), (3, 'Out of Bed'), (4, 'Light Sleep'), (5, 'Deep Sleep'), (6, 'REM Sleep'), (7, 'Awake in Bed')], default=0)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='diafit_backend.sleepsessionentity')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='sleepsessionentity',
            index=models.Index(fields=['user_id'], name='diafit_back_user_id_79a70a_idx'),
        ),
        migrations.AddIndex(
            model_name='sleepsessionentity',
            index=models.Index(fields=['source_id'], name='diafit_back_source__67987c_idx'),
        ),
        migrations.AddIndex(
            model_name='sleepstageentity',
            index=models.Index(fields=['session_id', 'start_time'], name='diafit_back_session_6221ae_idx'),
        ),
    ]
