# Generated by Django 5.2.7 on 2025-11-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diafit_backend', '0006_sleepsessionentity_sleepstageentity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepsessionentity',
            name='type',
            field=models.CharField(choices=[('NAP', 'Nap'), ('SLEEP', 'Sleep')], default='SLEEP', max_length=10),
        ),
    ]
