# Generated by Django 5.2.7 on 2025-11-10 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diafit_backend', '0007_sleepsessionentity_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRateEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('device', models.CharField(default='Unknown', max_length=100)),
                ('source', models.CharField(default='Unknown', max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id'], name='diafit_back_user_id_3f2d6b_idx'), models.Index(fields=['timestamp'], name='diafit_back_timesta_e8a8df_idx')],
            },
        ),
    ]
