# Generated by Django 5.2.7 on 2025-11-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diafit_backend', '0008_heartrateentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepsessionentity',
            name='device',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
